/**
 * 智能合约部署脚本
 * Deploy Script for E-Voting Smart Contracts
 *
 * 使用方法:
 *   本地: npx hardhat run scripts/deploy.js --network localhost
 *   测试网: npx hardhat run scripts/deploy.js --network sepolia
 */

const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("=".repeat(60));
  console.log("  区块链电子投票系统 - 智能合约部署");
  console.log("=".repeat(60));

  const [deployer] = await hre.ethers.getSigners();
  console.log("\n部署账户:", deployer.address);

  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log("账户余额:", hre.ethers.formatEther(balance), "ETH");

  // ============ 步骤 1: 部署 VoterRegistry ============
  console.log("\n" + "-".repeat(60));
  console.log("步骤 1: 部署 VoterRegistry 合约");
  console.log("-".repeat(60));

  const VoterRegistry = await hre.ethers.getContractFactory("VoterRegistry");
  const voterRegistry = await VoterRegistry.deploy();
  await voterRegistry.waitForDeployment();

  const voterRegistryAddress = await voterRegistry.getAddress();
  console.log("✓ VoterRegistry 部署成功");
  console.log("  地址:", voterRegistryAddress);

  // ============ 步骤 2: 部署 Voting ============
  console.log("\n" + "-".repeat(60));
  console.log("步骤 2: 部署 Voting 合约");
  console.log("-".repeat(60));

  const electionTitle = "2026 年度最佳员工评选";
  const electionDescription = "使用同态加密保护投票隐私";

  const Voting = await hre.ethers.getContractFactory("Voting");
  const voting = await Voting.deploy(
    voterRegistryAddress,
    electionTitle,
    electionDescription
  );
  await voting.waitForDeployment();

  const votingAddress = await voting.getAddress();
  console.log("✓ Voting 合约部署成功");
  console.log("  地址:", votingAddress);
  console.log("  标题:", electionTitle);

  // ============ 步骤 3: 部署 MerkleVerifier ============
  console.log("\n" + "-".repeat(60));
  console.log("步骤 3: 部署 MerkleVerifier 合约");
  console.log("-".repeat(60));

  const MerkleVerifier = await hre.ethers.getContractFactory("MerkleVerifier");
  const merkleVerifier = await MerkleVerifier.deploy();
  await merkleVerifier.waitForDeployment();

  const merkleVerifierAddress = await merkleVerifier.getAddress();
  console.log("✓ MerkleVerifier 部署成功");
  console.log("  地址:", merkleVerifierAddress);

  // ============ 步骤 4: 关联合约 ============
  console.log("\n" + "-".repeat(60));
  console.log("步骤 4: 关联 VoterRegistry 和 Voting 合约");
  console.log("-".repeat(60));

  const tx = await voterRegistry.setVotingContract(votingAddress);
  await tx.wait();
  console.log("✓ VoterRegistry.setVotingContract() 调用成功");

  // ============ 步骤 5: 保存合约地址 ============
  console.log("\n" + "-".repeat(60));
  console.log("步骤 5: 保存合约地址到 .env 和 frontend/config.js");
  console.log("-".repeat(60));

  // 更新 .env 文件
  const envPath = path.resolve(__dirname, "../.env");
  let envContent = fs.readFileSync(envPath, "utf8");

  // 移除旧的合约地址配置（如果存在）
  envContent = envContent.replace(/\n# ============ 合约地址[\s\S]*?(?=\n# ====|$)/, "");
  // 也移除可能残留的单独变量
  envContent = envContent.replace(/^VOTING_CONTRACT_ADDRESS=.*\n?/gm, "");
  envContent = envContent.replace(/^VOTER_REGISTRY_ADDRESS=.*\n?/gm, "");
  envContent = envContent.replace(/^MERKLE_VERIFIER_ADDRESS=.*\n?/gm, "");

  // 确保末尾有换行
  if (!envContent.endsWith("\n")) envContent += "\n";

  // 追加合约地址
  envContent += `
# ============ 合约地址 (由 deploy.js 自动生成) ============
VOTING_CONTRACT_ADDRESS=${votingAddress}
VOTER_REGISTRY_ADDRESS=${voterRegistryAddress}
MERKLE_VERIFIER_ADDRESS=${merkleVerifierAddress}
`;

  fs.writeFileSync(envPath, envContent);
  console.log("✓ 合约地址已写入 .env");

  // 生成 frontend/config.js
  const configContent = `// 合约配置 (由 deploy.js 自动生成，请勿手动修改)
// Generated by deploy.js - Do not edit manually
const CONTRACT_CONFIG = {
  VOTING_ADDRESS: "${votingAddress}",
  VOTER_REGISTRY_ADDRESS: "${voterRegistryAddress}",
  MERKLE_VERIFIER_ADDRESS: "${merkleVerifierAddress}",
  NETWORK: {
    name: "Sepolia",
    chainId: 11155111,
    chainIdHex: "0xaa36a7"
  }
};
`;

  const configPath = path.resolve(__dirname, "../frontend/config.js");
  fs.writeFileSync(configPath, configContent);
  console.log("✓ frontend/config.js 已生成");

  // ============ 部署总结 ============
  console.log("\n" + "=".repeat(60));
  console.log("  部署完成！合约地址汇总");
  console.log("=".repeat(60));
  console.log("\nVoterRegistry:", voterRegistryAddress);
  console.log("Voting:       ", votingAddress);
  console.log("MerkleVerifier:", merkleVerifierAddress);

  // 保存部署信息
  const deploymentInfo = {
    network: hre.network.name,
    deployer: deployer.address,
    timestamp: new Date().toISOString(),
    contracts: {
      VoterRegistry: voterRegistryAddress,
      Voting: votingAddress,
      MerkleVerifier: merkleVerifierAddress
    },
    election: {
      title: electionTitle,
      description: electionDescription
    }
  };

  console.log("\n部署信息 (JSON):");
  console.log(JSON.stringify(deploymentInfo, null, 2));

  return deploymentInfo;
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("部署失败:", error);
    process.exit(1);
  });
