/**
 * 本地一键部署脚本 (适用于 Hardhat 本地节点)
 * One-click local deployment for development and testing.
 *
 * 使用方法:
 *   1. 启动 Hardhat 节点: npx hardhat node
 *   2. 部署: npx hardhat run scripts/deploy-local.js --network localhost
 *
 * 自动完成:
 *   - 部署所有 5 个合约
 *   - 计算正确的 ElGamal 公钥 (sk = 12345678901234567890)
 *   - 添加 3 个候选人
 *   - 注册前 5 个测试账户为选民
 *   - 生成 frontend/config.js (localhost 配置)
 */

const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

// 固定的开发私钥 (仅用于本地测试, 勿在生产环境使用)
const ADMIN_SK = "12345678901234567890";

async function main() {
  console.log("=".repeat(60));
  console.log("  本地一键部署 - 区块链电子投票系统 (ZKP)");
  console.log("=".repeat(60));

  const signers = await hre.ethers.getSigners();
  const deployer = signers[0];
  console.log("\n管理员账户:", deployer.address);

  // ─── 步骤 1: 计算 ElGamal 公钥 ──────────────────────────
  console.log("\n[1/8] 计算 ElGamal 公钥 (sk * G)...");
  const circomlibjs = require("circomlibjs");
  const babyJub = await circomlibjs.buildBabyjub();
  const F = babyJub.F;

  const GENERATOR = [
    F.e(5299619240641551281634865583518297030282874472190772894086521144482721001553n),
    F.e(16950150798460657717958625567821834550301663161624707787222815936182638968203n)
  ];

  const pk = babyJub.mulPointEscalar(GENERATOR, BigInt(ADMIN_SK));
  const pkX = F.toObject(pk[0]).toString();
  const pkY = F.toObject(pk[1]).toString();
  console.log("  PK.x:", pkX.slice(0, 30) + "...");
  console.log("  PK.y:", pkY.slice(0, 30) + "...");
  console.log("  (对应私钥 sk =", ADMIN_SK, ")");

  // ─── 步骤 2: 部署 VoterRegistry ────────────────────────
  console.log("\n[2/8] 部署 VoterRegistry...");
  const VoterRegistry = await hre.ethers.getContractFactory("VoterRegistry");
  const voterRegistry = await VoterRegistry.deploy();
  await voterRegistry.waitForDeployment();
  const voterRegistryAddr = await voterRegistry.getAddress();
  console.log("  地址:", voterRegistryAddr);

  // ─── 步骤 3: 部署验证器合约 ────────────────────────────
  console.log("\n[3/8] 部署 VoteVerifier (ZKP1+ZKP2)...");
  const VoteVerifier = await hre.ethers.getContractFactory("VoteVerifier");
  const voteVerifier = await VoteVerifier.deploy();
  await voteVerifier.waitForDeployment();
  const voteVerifierAddr = await voteVerifier.getAddress();
  console.log("  地址:", voteVerifierAddr);

  console.log("\n[4/8] 部署 TallyVerifier (ZKP3)...");
  const TallyVerifier = await hre.ethers.getContractFactory("TallyVerifier");
  const tallyVerifier = await TallyVerifier.deploy();
  await tallyVerifier.waitForDeployment();
  const tallyVerifierAddr = await tallyVerifier.getAddress();
  console.log("  地址:", tallyVerifierAddr);

  // ─── 步骤 4: 部署 Voting ──────────────────────────────
  console.log("\n[5/8] 部署 Voting 合约...");
  const Voting = await hre.ethers.getContractFactory("Voting");
  const voting = await Voting.deploy(
    voterRegistryAddr,
    "2026 年度最佳员工评选",
    "使用零知识证明保护投票隐私 (本地测试)",
    voteVerifierAddr,
    tallyVerifierAddr,
    [pkX, pkY]
  );
  await voting.waitForDeployment();
  const votingAddr = await voting.getAddress();
  console.log("  地址:", votingAddr);

  // ─── 步骤 5: 部署 MerkleVerifier ──────────────────────
  console.log("\n[6/8] 部署 MerkleVerifier...");
  const MerkleVerifier = await hre.ethers.getContractFactory("MerkleVerifier");
  const merkleVerifier = await MerkleVerifier.deploy();
  await merkleVerifier.waitForDeployment();
  const merkleVerifierAddr = await merkleVerifier.getAddress();
  console.log("  地址:", merkleVerifierAddr);

  // ─── 步骤 6: 关联合约 + 添加候选人 ────────────────────
  console.log("\n[7/8] 初始化选举数据...");

  // 关联 VoterRegistry
  await (await voterRegistry.setVotingContract(votingAddr)).wait();
  console.log("  VoterRegistry -> Voting 关联完成");

  // 添加 3 个候选人
  const candidates = ["张三", "李四", "王五"];
  for (const name of candidates) {
    await (await voting.addCandidate(name)).wait();
    console.log("  候选人已添加:", name);
  }

  // 注册测试账户为选民 (账户 1-5)
  const voterAddresses = signers.slice(1, 6).map(s => s.address);
  await (await voterRegistry.registerVotersBatch(voterAddresses)).wait();
  console.log(`  已注册 ${voterAddresses.length} 个选民`);
  for (const addr of voterAddresses) {
    console.log("    -", addr);
  }

  // ─── 步骤 7: 生成 config.js ───────────────────────────
  console.log("\n[8/8] 生成 frontend/config.js (localhost)...");

  const configContent = `// 合约配置 (由 deploy-local.js 自动生成，请勿手动修改)
// Generated by deploy-local.js - Do not edit manually
const CONTRACT_CONFIG = {
  VOTING_ADDRESS: "${votingAddr}",
  VOTER_REGISTRY_ADDRESS: "${voterRegistryAddr}",
  MERKLE_VERIFIER_ADDRESS: "${merkleVerifierAddr}",
  VOTE_VERIFIER_ADDRESS: "${voteVerifierAddr}",
  TALLY_VERIFIER_ADDRESS: "${tallyVerifierAddr}",
  NETWORK: {
    name: "Localhost",
    chainId: 31337,
    chainIdHex: "0x7a69"
  },
  // ElGamal 公钥 (BabyJubJub 点)
  ELGAMAL_PK: {
    x: "${pkX}",
    y: "${pkY}"
  },
  // 开发用 ElGamal 私钥 (仅本地测试使用!)
  DEV_ADMIN_SK: "${ADMIN_SK}",
  // ZKP 资源路径
  ZKP: {
    VOTE_PROOF_WASM: "zk/vote_proof.wasm",
    VOTE_PROOF_ZKEY: "zk/vote_proof_final.zkey",
    TALLY_PROOF_WASM: "zk/tally_proof.wasm",
    TALLY_PROOF_ZKEY: "zk/tally_proof_final.zkey"
  }
};
`;

  const configPath = path.resolve(__dirname, "../frontend/config.js");
  fs.writeFileSync(configPath, configContent);
  console.log("  frontend/config.js 已生成");

  // ─── 部署总结 ─────────────────────────────────────────
  console.log("\n" + "=".repeat(60));
  console.log("  部署完成! 下一步:");
  console.log("=".repeat(60));
  console.log("\n  1. 启动后端服务:");
  console.log("     python -m uvicorn server:app --port 8000");
  console.log("\n  2. 打开浏览器:");
  console.log("     投票页面: http://localhost:8000/");
  console.log("     管理页面: http://localhost:8000/admin");
  console.log("\n  3. MetaMask 配置:");
  console.log("     网络: http://127.0.0.1:8545 (Chain ID: 31337)");
  console.log("     导入测试私钥 (Hardhat 默认账户)");
  console.log("\n  4. 管理员操作 (在 /admin 页面):");
  console.log("     - 候选人已添加: " + candidates.join(", "));
  console.log("     - 选民已注册: 账户 1-5");
  console.log("     - 点击'启动选举'开始投票");
  console.log("     - 计票时使用 ElGamal 私钥:", ADMIN_SK);
  console.log("\n" + "=".repeat(60));
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("部署失败:", error);
    process.exit(1);
  });
